# ---------------------------------------
#              dark power
# ---------------------------------------
[[plugins]]                                    
repo = 'Shougo/dein.vim' 


# ---------------------------------------
#             colorscheme ayu
# ---------------------------------------
[[plugins]]
repo = 'ayu-theme/ayu-vim'
name = 'ayu'


# ---------------------------------------
#           colorscheme aylin
# ---------------------------------------
# to change change specific color, you have to declare before set colorscheme
[[plugins]]
repo = 'AhmedAbdulrahman/aylin.vim'
name = 'aylin'
hook_add = '''
  autocmd ColorScheme * highlight Comment ctermfg=220 guisp=#c9083f
  highlight Normal ctermbg=none guibg=NONE
  highlight NonText ctermbg=none guibg=NONE
  highlight LineNr ctermbg=none guibg=NONE
  highlight Folded ctermbg=none guibg=NONE
  highlight EndOfBuffer ctermbg=none guibg=NONE
'''

# ---------------------------------------
#         colorscheme  gruvbox
# ---------------------------------------
[[plugins]] 
repo = "morhetz/gruvbox"
name = "gruvbox"


# ---------------------------------------
#        NLKNguyen/papercolor-theme
# ---------------------------------------
[[plugins]] 
repo = "NLKNguyen/papercolor-theme"
name = "papercolor-theme"

# ---------------------------------------
#               背景透過
# ---------------------------------------
[[plugins]] 
repo = 'miyakogi/seiya.vim'
    

# ---------------------------------------
#               indentLine
# ---------------------------------------
[[plugins]]
repo = 'Yggdroot/indentLine'


# ---------------------------------------
#             vim-js-indent
#             js ts indent
# ---------------------------------------
[[plugins]]
repo = "jason0x43/vim-js-indent"


# ---------------------------------------
#             vim-javascript
# ---------------------------------------
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'javascript.jsx']
hook_add = """
let g:javascript_indent_disable = 1
"""

# ---------------------------------------
#             vim-styled-jsx
# ---------------------------------------
[[plugins]]
repo = 'alampros/vim-styled-jsx'
on_ft = ['javascript', 'javascript.jsx']


# -----------------------------------------
#           colorscheme dracula
# -----------------------------------------
[[plugins]]
repo = 'dracula/vim'
name = 'dracula'

[[plugins]]
repo = 'tobyS/pdv'

[[plugins]]
repo = 'tobyS/vmustache'


# -----------------------------------------
#           colorscheme solarized
# -----------------------------------------
[[plugins]]
repo = 'altercation/vim-colors-solarized'


# ---------------------------------------
#         colorscheme Zenburn
# ---------------------------------------
[[plugins]] 
repo = "jnurmine/Zenburn"
name = "zenburn"


# -----------------------------------------
#            Fugitive Settings
# -----------------------------------------
#  git plugin
#  command list
#  Gstatus
#  Gwrite
#  Gcommit
#  Gblame
#  Gdiff
#  Gmerge
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = """
source ~/.config/nvim/plugins/plugins-vim-fugitive.vim
"""


# -----------------------------------------
#              Git Gutters
#          < show diff + - ~ >
# -----------------------------------------
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = """
  set updatetime=100
  set signcolumn=yes
"""


# -----------------------------------------
#             openbrowser.vim
# -----------------------------------------
[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'tpope/vim-rhubarb'


# -----------------------------------------
#               ultisnips 
# -----------------------------------------
# [[plugins]]
# repo = 'SirVer/ultisnips'
# hook_add = """
# let g:UltiSnipsSnippetDirectories="~/.config/nvim/plugins/S/"
# """


[[plugins]]
repo = 'vim-snippets'

[[plugins]]
repo = 'mlaursen/vim-react-snippets'

[[plugins]]
repo = 'Galooshi/import-js'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'leafgarland/typescript-vim'
hook_add = """
let g:typescript_indent_disable = 1
"""

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'

[[plugins]]
repo = 'easymotion/vim-easymotion'

# -----------------------------------------
#               CocSettings
# -----------------------------------------
#  tabとshift+tabで補完候補切り替え
#  CRで確定
# [[plugins]]                                    
# repo = "neoclide/coc.nvim"
# merge = 0
# rev  = "release"
# hook_add = """
# source ~/.config/nvim/plugins/coc.rc.vim
# """

# [[plugins]]
# repo = "Shougo/defx.nvim"
# depends = ["defx-git", 'defx.icons']
# hook_add = """
#  source ~/.config/nvim/plugins/defx.rc.vim
# """

# [[plugins]]
# repo = 'kristijanhusak/defx-icons'

# [[plugins]]
# repo = 'kristijanhusak/defx-git'

# [[plugins]]
# repo = "Shougo/denite.nvim"
# hook_add = """
#   source ~/.config/nvim/plugins/denite.rc.vim
# """

# [[plugins]]
# repo = 'Shougo/deoppet.nvim'

# [[plugins]]
# repo = "Shougo/neocomplete.vim"

# [[plugins]]
# repo = 'dart-lang/dart-vim-plugin'

# [[plugins]]
# repo = 'thosakwe/vim-flutter'

# ---------------------------------------
#             comment plugin
# ---------------------------------------
# コメントが便利になる
# gccで現在の行をコメントアウト
# visualでgcで選択している行をコメントアウト
[[plugins]]
repo = "tpope/vim-commentary"

# ---------------------------------------
#              undo plugin
# ---------------------------------------
# [[plugins]]
# repo = 'mbbill/undotree'
# hook_add = """
# nmap <F5> :Und<CR>
# """

# [[plugins]]
# repo = 'tpope/vim-surround'
# "Hello world!" cs"' -> 'Hello world!'
# ds' -> Hello world!のように'を削除
# 矩形ビジュアルモードでHello world!を選択した後でS"を入力すると"Hello world!"のように"で囲むことができる


# -----------------------------------------
#           neovim terminal 強化
# -----------------------------------------
# :Tnew -> open terminal
# :T(command) -> execute command
# C-w -> exit terminal mode.
[[plugins]]
repo = 'kassio/neoterm'
hook_add = """
  let g:neoterm_default_mod='belowright'
  let g:neoterm_size=10
  let g:neoterm_autoscroll=1
  tnoremap <silent> <C-w> <C-\><C-n><C-w>
"""

# -----------------------------------------
#          自作CheatSheet plugin
# -----------------------------------------
# :Cheat -> open cheatsheet
[[plugins]]
repo = 'reireias/vim-cheatsheet'
hook_add = """
  let g:cheatsheet#cheat_file = '~/.config/nvim/cheatsheet.md'
"""

# -----------------------------------------
#          supertab (tab補完)
# -----------------------------------------
[[plugins]]
repo = 'ervandew/supertab'


# -----------------------------------------
#             vim-repeat .
# -----------------------------------------
[[plugins]]
repo = "tpope/vim-repeat"


# -----------------------------------------
#             vim-easy-align 
# -----------------------------------------
# [[plugins]]
# repo = "junegunn/vim-easy-align"
# hook_add = """
# " Start interactive EasyAlign in visual mode (e.g. vipga)
# xmap ga <Plug>(EasyAlign)

# " Start interactive EasyAlign for a motion/text object (e.g. gaip)
# nmap ga <Plug>(EasyAlign)
# """


# -----------------------------------------
#         vim-highlightedyank 
# -----------------------------------------
[[plugins]]
repo = 'machakann/vim-highlightedyank'
hook_add = """
let g:highlightedyank_highlight_duration = 1000
"""


# ---------------------------------------
#               phpactor
# ---------------------------------------
# [[plugins]]
# repo = 'phpactor/phpactor'
# on_ft = ['php']
# build = 'composer install'


# ---------------------------------------
#            preview-markdown
# ---------------------------------------
# use glow for preview markdown
# [[plugins]]
# repo = "skanehira/preview-markdown.vim"
# hook_add = """
# let g:preview_markdown_auto_update = 1
# """


# ---------------------------------------
#             fzf install
# ---------------------------------------
[[plugins]] 
repo = "junegunn/fzf"
build = './install --all'

# ---------------------------------------
#               fzf.vim
# ---------------------------------------
[[plugins]]
repo = 'junegunn/fzf.vim'


# ---------------------------------------
#               nerdtree
# ---------------------------------------
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  let g:NERDTreeShowBookmarks=1
  let g:NERDTreeShowHidden = 1
  let g:NERDTreeDirArrows = 1
  let NERDTreeIgnore = ['\.git$', 'node_modules']
  autocmd StdinReadPre * let s:std_in=1
  map <C-a> :NERDTreeToggle<CR>
'''

# ---------------------------------------
#               nerdtree
# ---------------------------------------
[[plugins]] 
repo = "preservim/nerdtree"


# ---------------------------------------
#              vim-blade
# ---------------------------------------
[[plugins]] 
repo = "jwalton512/vim-blade"
hook_add = """
let g:blade_custom_directives = ['datetime', 'javascript']
let g:blade_custom_directives_pairs = {
      \   'markdown': 'endmarkdown',
      \   'cache': 'endcache',
      \ }
"""

# ---------------------------------------
#             alvan/vim-closetag
# ---------------------------------------
[[plugins]] 
repo = "alvan/vim-closetag"
hook_add = """
let g:closetag_filenames = '*.html,*.xhtml,*.phtml, *.php'
let g:closetag_xhtml_filenames = '*.xhtml,*.jsx'
let g:closetag_filetypes = 'html,xhtml,phtml, *.php'
let g:closetag_xhtml_filetypes = 'xhtml,jsx'
let g:closetag_emptyTags_caseSensitive = 1
let g:closetag_regions = {
    \ 'typescript.tsx': 'jsxRegion,tsxRegion',
    \ 'javascript.jsx': 'jsxRegion',
    \ 'typescriptreact': 'jsxRegion,tsxRegion',
    \ 'javascriptreact': 'jsxRegion',
    \ }
"""


# ---------------------------------------
#             vim-cyberpunk
# ---------------------------------------
[[plugins]] 
repo = "thedenisnikulin/vim-cyberpunk"
name="cyberpunk"


# ---------------------------------------
#             shadotheme
# ---------------------------------------
[[plugins]] 
repo = "Shadorain/shadotheme"
name = "shadotheme"
hook_add = """"
 autocmd ColorScheme * highlight Comment ctermfg=220 guisp=#c9083f
 colorscheme xshado
"""


# ---------------------------------------
#           ulwlu/abyss.vim
# ---------------------------------------
[[plugins]] 
repo = "ulwlu/abyss.vim"
name = "abyss"


# ---------------------------------------
#        bignimbus/pop-punk.vim
# ---------------------------------------
[[plugins]] 
repo = "bignimbus/pop-punk.vim"
name = "pop-punk"


# ---------------------------------------
#        neovim/nvim-lspconfig
# ---------------------------------------
[[plugins]] 
repo = "neovim/nvim-lspconfig"

